modLoader = "javafml"
loaderVersion = "[38,)"
license = "All Rights Reserved"
[[mods]]
modId = "hoporp"
version = "1.3.1"
displayName = "HopoBetterRuinedPortals"
credits = ""
authors = "Hoponopono"
description = ""